### ISSUE TITLE
Data import

### ISSUE THREAD

**Issue by VanishMax** [IU-MAP/project-les-frais#12]
**Description:** As a new user, I want to import my existing data into the app, so I can start working with it faster.

**Priority:** Secondary. This feature is important but not a blocker for any other user stories. Developers of this feature might work synchronously with any other user story in development.

Scale proposal, the [MoSCoW method](https://paper-leaf.com/insights/prioritize-user-stories/)
1. _**Must have:** Accept .XLS and .XLSX files, parse them and insert found columns into a table of transactions._
2. _**Should Have**: Feature that asks user to specify the columns of the file to import more accurately._
3. _**Could have**: .csv file import._
4. _**Won't have**: .pdf file import._

**Subtasks:**
- [x] Implement frontend Import feature #9 
- [ ] Test the frontend Import data feature #10 
- [x] Implement and test backend Import data feature #11 

**Estimation:** 1 sprint that takes a week.

**Acceptance criteria**

```
Feature: Data import
Given I'm on the settings page
Then I click the "Import data" link
And read the information about the import
And click the button "Import .XLS"
And choose the file to import from the computer that has at least 4 columns in any order that has the following fields: date, name, category name and price.
And select in a table the correspondence of columns to real data fields.
And press the button "Import"
Then I am redirected to the authorized dashboard page with more transactions in it due to the newly imported transactions.
```
