### ISSUE TITLE
Add transactions

### ISSUE THREAD

**Issue by VanishMax** [IU-MAP/project-les-frais#17]
**Description:** As an authorized user, I want to keep track of my incomes and expenses.

**Priority:** Major. This feature is basic functionality of the application therefore very important.

Scale proposal, the [MoSCoW method](https://paper-leaf.com/insights/prioritize-user-stories/)
1. _**Must have:** Add incomes and expenses._
2. _**Should Have**:  –_
3. _**Could have**: Transaction selection and removal_
4. _**Won't have**:  –._

**Subtasks:**
- [x] Add backend CRUD endpoints for transaction entity and test it #13 
- [x] Implement transaction creation on the frontend #14 
- [x] Implement transaction selection, edition and removal on the frontend #15 
- [x] Test transaction components and logic on the frontend #16 

**Estimation:** 1 sprint that takes a week.

**Acceptance criteria**

```
Feature: Transaction addition
Given I'm on the authorized dashboard page
Then I select what I want to add: gain or loss of money transaction
And I type the name of the transaction
And type the price of it
And select additional fields: category, date, currency, and type optional description
And press the "Add transaction" button
Then I should see the newly created transaction in the list.
```

```
Feature: Transactions removal
Given I'm on the authorized dashboard page
Then I view the the transaction list and point the mouse over a transaction item, so the three-dots-icon is displayed
And I press this button viewing the menu of actions: Edit, Select, Remove
And I press the "Select" option. This transaction item is selected visually now
Then I click on more items in the list
And press the trash bin icon button
And I see that selected transactions are removed
```
