### ISSUE TITLE
Switch default currency

### ISSUE THREAD

**Issue by Andrey862** [IU-MAP/project-les-frais#25]
**Title:**  Switching users default currency setting

**Description:**
Each user has a default currency that they can change in the settings. When the user checks the statistics all the transactions converted  to the user's default currency

**As an**  international user, **I want** to add expenses of different currencies and see the statistics of amounts of money that are converted to the default currency, **so that** I don't get confused between currencies.

**Priority:** Important

Scale proposal, the [MoSCoW method] (https://paper-leaf.com/insights/prioritize-user-stories/)

1. _**Must have:** Support of US dollar and Russian rouble. Using up-to-date exchange rates. ._
2. _**Should Have**: Ideally, the first version of this product has this feature, but it is not absolutely necessary. They can be as important, but not as critical in terms of time, as the "Must Have" ._
3. _**Could have**: Support for European currencies
4. _**Won't have**: -_

**Estimate:** 1/2-1 sprint

**Subtasks:** 
- [ ] implement on the frontend in the settings page #26
- [ ] store user's default currency #27
- [ ] automatically convert statistics to the user's default currency #28

|**Acceptance criteria**|
|---|
|**Given** that I'm an authorized user <br>**When** I change my default currency <br>**Then** It stays next time I log in <be>|
|**Given** that I'm an authorized user <br>**When** I change my default currency <br>**Then** the statistics <be>|
