### ISSUE TITLE
Add expense templates

### ISSUE THREAD

**Issue by matveyplevako** [IU-MAP/project-les-frais#29]
**Description:** As an authorized user, I want to improve the speed of adding new expenses by having their templates with pre-existing description, price etc.

**Priority:** Secondary. It just improves the user experience, but can be left behind.

**Estimate:** 1 sprint

**Subtasks:**
- [x] Implement and test frontend for creating templates #30 
- [x] Implement and test frontend for suggesting templates #31 
- [x] Implement and test backend for saving templates #32 
- [x] Implement and test backend for searching templates #33 

**Estimation:** 1 sprint that takes a week.

**Acceptance criteria**

```
Feature: Add expense templates
Given I'm on the settings page
Then I click the "Create template" link
And add information about the template
And click the button save
Then template is saved.


Given I'm on the main page
Then I click the "add spending" link
And start typing information about spending
Then suggested template is shown.
```
