### ISSUE TITLE
Authorization and registration

### ISSUE THREAD

**Issue by VanishMax** [IU-MAP/project-les-frais#8]
**Description:** As a user, I want to log into the app, so I can view my personal expenses data.

**Priority:** Major. This feature is required to be implemented before the beginning of User Stories for authorized users.

Scale proposal, the [MoSCoW method](https://paper-leaf.com/insights/prioritize-user-stories/)
1. _**Must have:** Log In and Sign Up features._
2. _**Should Have**: Update password after authorization._
3. _**Could have**: Reset password when a user forgets it._
4. _**Won't have**: –_

**Subtasks:**
- [x] Set up the frontend part of the application #2 
- [x] Set up the backend part of the application #3 
- [x] Implement frontend authentication #4 
- [x] Test frontend authentication #5 
- [x] Test backend authentication #44 
- [x] Implement backend authentication endpoints #6 
- [x] Set up CI/CD, deploy the application #7 

**Estimation:** 1 sprint that takes a week.

**Acceptance criteria**

```
Feature: Sign Up
Given I'm on the Sign Up page
And I am unauthorized
And do not have an account
Then I fill the "E-mail" field
And fill the "Password" field
And fill the "Confirm Password" with the same content as in the "Password"
And press the "Submit" button
If the email is correct and the password are the same and longer than 8 symbols
Then I am redirected to the authenticated dashboard page
```

```
Feature: Log In
Given I'm on the Log In page
And I am unauthorized
But I have an account
Then I fill the "E-mail" field
And fill the "Password" field
And press "Submit" button
If the email exists and the password hash matches the saved hash in the database
Then I am redirected to the authenticated dashboard page
```
